name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    # https://crontab.guru/#54_6-18/4_*_*_MON-THU : Run every 4 hours
    - cron: "54 6-18/4 * * MON-THU"

  # For debugging purposes, allow manual triggering
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.22.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
